baseURL = "https://kemrictomta.github.io/cloud-security-learning/"
languageCode = "en"
title = "KemricTomta â€” Cloud & Security Learning"
theme = "hugo-blog-awesome"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  defaultColor = "auto"
  description = "Documenting my cloud & cybersecurity learning journey: labs, notes, and projects."

  # Optional nice touches (if theme supports)
  mainSections = ["posts"]

# Tags support (URLs like /tags/security/)
[taxonomies]
  tag = "tags"

# Main navigation
[menu]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 5

  [[menu.main]]
    name = "Learning"
    pageRef = "pages/learning"
    weight = 10

  [[menu.main]]
    name = "Stack"
    pageRef = "pages/stack"
    weight = 20

  [[menu.main]]
    name = "Case Study"
    pageRef = "pages/case-study"
    weight = 30

  [[menu.main]]
    name = "Posts"
    pageRef = "posts"
    weight = 40
